### ISSUE TITLE
Error Log vom 05.02.2015

### ISSUE THREAD

**Issue by MysticCity** [MysticCity/Ancient#154]
[18:35:27 WARN]: java.lang.NullPointerException
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Commands.PotionEffectCommand.getTypeByName(PotionEffectCommand.java:48)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Commands.PotionEffectCommand.playCommand(PotionEffectCommand.java:25)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Command.executeCommand(Command.java:60)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:452)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Command.executeCommand(Command.java:63)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:452)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Command.executeCommand(Command.java:63)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:452)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.IfSection.executeCommand(IfSection.java:65)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:452)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.IfSection.executeCommand(IfSection.java:65)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:452)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Command.executeCommand(Command.java:63)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection$1.run(CodeSection.java:49)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.AncientRPG.scheduleThreadSafeTask(AncientRPG.java:452)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.CodeSection.executeCommand(CodeSection.java:47)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Spell.execute(Spell.java:670)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Spells.Commands.CommandPlayer.scheduleSpell(CommandPlayer.java:24)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Classes.Commands.ClassCastCommand.processCast(ClassCastCommand.java:66)
[18:35:27 WARN]:        at com.ancientshores.AncientRPG.Listeners.AncientRPGPlayerListener.onPlayerInteract(AncientRPGPlayerListener.java:448)
[18:35:27 WARN]:        at sun.reflect.GeneratedMethodAccessor253.invoke(Unknown Source)
[18:35:27 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:35:27 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[18:35:27 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292)
[18:35:27 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:35:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[18:35:27 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[18:35:27 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:216)
[18:35:27 WARN]:        at org.bukkit.craftbukkit.v1_7_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:186)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:605)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.a(SourceFile:60)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.PacketPlayInBlockPlace.handle(SourceFile:9)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469)
[18:35:27 WARN]:        at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)

**Comment by MysticCity** [comment]
hier nochmal: http://pastebin.com/gcydju2S

**Comment by MysticCity** [comment]
Fast alle Spells haben folgendes: 
[18:40:15 WARN]: java.lang.NullPointerException

**Comment by MysticCity** [comment]
[18:40:15 WARN]: java.lang.NullPointerException

**Comment by MysticCity** [comment]
[18:40 :15  WARN]: jav a. lang . Null Pointer Exception

Nun Aber
